name: Merge Sonrası Testler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları çek
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Paketleri yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install pytest requests

    - name: Testleri çalıştır
      run: pytest --html=rapor.html --self-contained-html
